version: '3.4'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: conciergeAPI
    ports:
      - 8083:80
      - 8084:443
    volumes:
      - ~/.aspnet/https:/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${SSLPASS}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx