name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{ github.workspace }}/ConciergeBackend/appsettings.json'
      env:
        ConnectionStrings.localConnString: ${{secrets.LOCAL_DB}}
        AppSettings.Token: ${{secrets.API_TOKEN}}
    
          
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.CANISTERIO_USER}}
        DOCKER_PASSWORD: ${{secrets.CANISTERIO_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD cloud.canister.io:5000
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and push
      uses: opspresso/action-docker@master
      # with:
      env:
        USERNAME: ${{ secrets.CANISTERIO_USER }}
        PASSWORD: ${{ secrets.CANISTERIO_PASSWORD }}
        REGISTRY: cloud.canister.io:5000
        IMAGE_NAME: ${{ secrets.CANISTERIO_USER }}/conciergeapi
        DOCKERFILE: ./ConciergeBackend/Dockerfile
        LATEST: "true" 

      
    
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:  
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.CANISTERIO_USER}}
          DOCKER_PASSWORD: ${{secrets.CANISTERIO_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD cloud.canister.io:5000
        
      - name: Deploy Docker container to Ubuntu Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            docker login -u ${{secrets.CANISTERIO_USER}} -p ${{secrets.CANISTERIO_PASSWORD}} cloud.canister.io:5000            
            docker stop conciergebackend  || true
            docker rm  conciergebackend || true
            docker pull cloud.canister.io:5000/pacebrian0/conciergeapi:latest
            cd concierge
            docker run -d --name conciergebackend --network=concierge_network --ip 10.5.0.7 -e ASPNETCORE_URLS=http://+:5000  cloud.canister.io:5000/pacebrian0/conciergeapi:latest
      
#       uses: docker/build-push-action@v3
#       with:
#           context: .
#           file: ./ConciergeBackend/Dockerfile
#           push: true
#           registry: cloud.canister.io:5000
#           tags:  ${{secrets.CANISTERIO_USER}}/conciergeapi:latest
