name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.CANISTERIO_USER}}
        DOCKER_PASSWORD: ${{secrets.CANISTERIO_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD cloud.canister.io:5000
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and push
      uses: opspresso/action-docker@master
      # with:
      env:
        USERNAME: ${{ secrets.CANISTERIO_USER }}
        PASSWORD: ${{ secrets.CANISTERIO_PASSWORD }}
        REGISTRY: cloud.canister.io:5000
        IMAGE_NAME: ${{ secrets.CANISTERIO_USER }}/conciergeapi
        DOCKERFILE: ./ConciergeBackend/Dockerfile
        LATEST: "true" 

      
    
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:  
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.CANISTERIO_USER}}
          DOCKER_PASSWORD: ${{secrets.CANISTERIO_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD cloud.canister.io:5000
        
      - name: Deploy Docker container to Ubuntu Server
        uses: appleboy/ssh-action@master
        env:
          DOCKER_USER: ${{secrets.CANISTERIO_USER}}
          DOCKER_PASSWORD: ${{secrets.CANISTERIO_PASSWORD}}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            docker login --username=$DOCKER_USER --password=$DOCKER_PASSWORD cloud.canister.io:5000
            echo "1"
            docker stop cloud.canister.io:5000/pacebrian0/conciergeweb || true
            echo "2"
            docker rm cloud.canister.io:5000/pacebrian0/conciergeweb || true
            echo "3"
            docker pull cloud.canister.io:5000/pacebrian0/conciergeweb
            echo "4"
            cd concierge
            docker run -d --name conciergebackend -e ASPNETCORE_URLS=http://+:5000 cloud.canister.io:5000/pacebrian0/conciergeweb:latest
      
#       uses: docker/build-push-action@v3
#       with:
#           context: .
#           file: ./ConciergeBackend/Dockerfile
#           push: true
#           registry: cloud.canister.io:5000
#           tags:  ${{secrets.CANISTERIO_USER}}/conciergeapi:latest
