name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: edit connection string
      uses: benday-inc/edit-dbconnstr-in-appsettings@main
      with:
        pathtosettingsfile: '${{ github.workspace }}/ConciergeBackend/appsettings.json'
        name: "localConnString"
        connectionstring: "${{secrets.LOCAL_DB}}"
          
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.CANISTERIO_USER}}
        DOCKER_PASSWORD: ${{secrets.CANISTERIO_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD cloud.canister.io:5000
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and push
      uses: opspresso/action-docker@master
      # with:
      env:
        USERNAME: ${{ secrets.CANISTERIO_USER }}
        PASSWORD: ${{ secrets.CANISTERIO_PASSWORD }}
        REGISTRY: cloud.canister.io:5000
        IMAGE_NAME: ${{ secrets.CANISTERIO_USER }}/conciergeapi
        DOCKERFILE: ./ConciergeBackend/Dockerfile
        LATEST: "true" 

      
    
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:  
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.CANISTERIO_USER}}
          DOCKER_PASSWORD: ${{secrets.CANISTERIO_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD cloud.canister.io:5000
        
      - name: Deploy Docker container to Ubuntu Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            docker login -u ${{secrets.CANISTERIO_USER}} -p ${{secrets.CANISTERIO_PASSWORD}} cloud.canister.io:5000            
            container= docker ps | grep conciergeweb | cut -d " " -f 4
            echo $container
            docker stop $container  || true
            docker rm $container || true
            docker pull cloud.canister.io:5000/pacebrian0/conciergeweb
            cd concierge
            docker run -d --name conciergebackend --network=concierge_network -e ASPNETCORE_URLS=http://+:5000  cloud.canister.io:5000/pacebrian0/conciergeweb:latest
      
#       uses: docker/build-push-action@v3
#       with:
#           context: .
#           file: ./ConciergeBackend/Dockerfile
#           push: true
#           registry: cloud.canister.io:5000
#           tags:  ${{secrets.CANISTERIO_USER}}/conciergeapi:latest
