name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.CANISTERIO_USER}}
        DOCKER_PASSWORD: ${{secrets.CANISTERIO_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD cloud.canister.io:5000
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and push
      uses: opspresso/action-docker@master
      # with:
      env:
        # username: ${{ secrets.DOCKER_USERNAME }}
        USERNAME: ${{ secrets.CANISTERIO_USER }}
        # password: ${{ secrets.DOCKER_PASSWORD }}
        PASSWORD: ${{ secrets.CANISTERIO_PASSWORD }}
        # registry: cloud.canister.io:5000
        REGISTRY: cloud.canister.io:5000
        # repository: ip2024/uz-server
        IMAGE_NAME: ${{ secrets.CANISTERIO_USER }}/uzconciergeapiserver
        # dockerfile: server/Dockerfile
        DOCKERFILE: ./ConciergeBackend/Dockerfile
        # tags: latest
        LATEST: "true" 

      
      
      
      
#       uses: docker/build-push-action@v3
#       with:
#           context: .
#           file: ./ConciergeBackend/Dockerfile
#           push: true
#           registry: cloud.canister.io:5000
#           tags:  ${{secrets.CANISTERIO_USER}}/conciergeapi:latest
